services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./proto:/var/www/proto
    ports:
      - "6001:6001"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network
  
  envoy:
    image: envoyproxy/envoy:dev
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
    ports:
      - "9901:9901"
      - "8080:8080"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge