<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto

namespace GPBMetadata;

class Message
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xBA\x01\x0A\x0Dmessage.proto\"\x1A\x0A\x07Message\x12\x0F\x0A\x07message\x18\x01 \x01(\x09\"!\x0A\x0EMessageRequest\x12\x0F\x0A\x07message\x18\x01 \x01(\x09\"\"\x0A\x0FMessageResponse\x12\x0F\x0A\x07message\x18\x01 \x01(\x092>\x0A\x0EMessageService\x12,\x0A\x07Message\x12\x0F.MessageRequest\x1A\x10.MessageResponseb\x06proto3", true);

        static::$is_initialized = true;
    }
}
