/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: message.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./message_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.MessageServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.MessageServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.MessageRequest,
 *   !proto.MessageResponse>}
 */
const methodDescriptor_MessageService_Message = new grpc.web.MethodDescriptor(
  '/MessageService/Message',
  grpc.web.MethodType.UNARY,
  proto.MessageRequest,
  proto.MessageResponse,
  /**
   * @param {!proto.MessageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.MessageResponse.deserializeBinary
);


/**
 * @param {!proto.MessageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.MessageResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.MessageResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.MessageServiceClient.prototype.message =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/MessageService/Message',
      request,
      metadata || {},
      methodDescriptor_MessageService_Message,
      callback);
};


/**
 * @param {!proto.MessageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.MessageResponse>}
 *     Promise that resolves to the response
 */
proto.MessageServicePromiseClient.prototype.message =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/MessageService/Message',
      request,
      metadata || {},
      methodDescriptor_MessageService_Message);
};


module.exports = proto;

