<?php

// Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
// source: message.proto

use Spiral\RoadRunner\GRPC;

interface MessageServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = 'MessageService';

    /**
     * @throws GRPC\Exception\InvokeException
     */
    public function Message(GRPC\ContextInterface $ctx, \MessageRequest $in): \MessageResponse;
}
