<?php

// Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
// source: ping.proto

use Spiral\RoadRunner\GRPC;

interface PingServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = 'PingService';

    /**
     * @throws GRPC\Exception\InvokeException
     */
    public function Ping(GRPC\ContextInterface $ctx, \PingRequest $in): \PingResponse;
}
